enedis:
  username: "myenedisuser"
  password: "myenedispassword"
  timesheets:
    - [ "00:00", "06:30" ]

influxdb:
  host: "localhost"
  port: 123
  username: "myinfludbuser"
  password: "myinfludbpassword"
  database: "mydatabase"
  measurement-prefix: "linky_"